---
- name: Look up GitHub SSH host key.
  local_action: command ssh-keyscan -t rsa github.com
  become: no
  register: github_ssh_keyscan_result
  changed_when: false # read-only task
  always_run: yes # for check mode
  run_once: yes # only run once on the ansible contrller

- name: Ensure github.com is a known host.
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: github.com
    key: "{{ github_ssh_keyscan_result.stdout }}"
  become: yes
