---
- name: Install homeshick
  git:
    repo: https://github.com/andsens/homeshick
    dest: "~{{ dotfiles_username }}/.homesick/repos/homeshick"

- name: Update bashrc to have homeshick initialization
  lineinfile:
    dest: "~{{ dotfiles_username }}/.bashrc"
    line: 'source "$HOME/.homesick/repos/homeshick/homeshick.sh"'
    regexp: 'homeshick'
    create: yes

- name: Check whether dotfiles directory exists.
  stat:
    path: "~{{ dotfiles_username }}/.homesick/repos/dotfiles"
  register: dotfiles_directory_results

- name: Clone dotfiles repo.
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "~{{ dotfiles_username }}/.homesick/repos/dotfiles"
  register: clone_dotfiles_result

- name: Create symlinks for dotfiles.
  command: "~{{ dotfiles_username }}/.homesick/repos/homeshick/bin/homeshick link dotfiles -f -q"
  when: clone_dotfiles_result.changed

