---
- name: Install homeshick
  git:
    repo: https://github.com/andsens/homeshick
    dest: "~{{ dotfiles_username }}/.homesick/repos/homeshick"

- name: Clone dotfiles repo.
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "~{{ dotfiles_username }}/.homesick/repos/dotfiles"
    version: "{{ dotfiles_repo_version }}"
    force: "{{ dotfiles_force_clone }}"
  register: clone_dotfiles_result
  # The Ansible host will often have local dotfiles changes; press on.
  ignore_errors: "{{ true if ansible_connection == 'local' else false }}"

- name: Create symlinks for dotfiles.
  shell: >
    ~{{ dotfiles_username|quote }}/.homesick/repos/homeshick/bin/homeshick
    symlink dotfiles --force --verbose
    | awk '{ print $2 }' | sort | uniq
  register: symlink_dotfiles_result
  changed_when: "'identical' not in symlink_dotfiles_result.stdout"
